### ISSUE TITLE
Path problem

### ISSUE THREAD

**Issue by torgem** [PockyBum522/net-simple-free-pdf-printer#1]
When an application is published as a Single File Executable, the following code will return an empty string:
return Path.GetDirectoryName(Assembly.GetExecutingAssembly().GetModules()[0].FullyQualifiedName);

The app then is looking for C:\lib\... for the GS-DLL. Root + Path.
Suggestion: Path.GetDirectoryName(Environment.ProcessPath)

**Comment by PockyBum522** [comment]
Please try 1.7.17 or later on nuget. It should be fixed. Let me know results so I can close this if it's working now.
